<?php

use App\Models\Country;

require_once('MySeeder.php');

class CountrySeeder extends MySeeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $query = "
        INSERT INTO country(id, name,code, status) VALUES(1,'Afganistan','Afganistan',1);
        INSERT INTO country(id, name,code, status) VALUES(2,'Alaska','Alaska',1);
        INSERT INTO country(id, name,code, status) VALUES(3,'Albania','Albania',1);
        INSERT INTO country(id, name,code, status) VALUES(4,'Algeria','Algeria',1);
        INSERT INTO country(id, name,code, status) VALUES(5,'American Samoa','American Samoa',1);
        INSERT INTO country(id, name,code, status) VALUES(6,'American Virgin IsI','American Virgin IsI',1);
        INSERT INTO country(id, name,code, status) VALUES(7,'Andorra','Andorra',1);
        INSERT INTO country(id, name,code, status) VALUES(8,'Angola','Angola',1);
        INSERT INTO country(id, name,code, status) VALUES(9,'Anguilla','Anguilla',1);
        INSERT INTO country(id, name,code, status) VALUES(10,'Antigua Barbuda','Antigua Barbuda',1);
        INSERT INTO country(id, name,code, status) VALUES(11,'Argentina','Argentina',1);
        INSERT INTO country(id, name,code, status) VALUES(12,'Armenia','Armenia',1);
        INSERT INTO country(id, name,code, status) VALUES(13,'Aruba','Aruba',1);
        INSERT INTO country(id, name,code, status) VALUES(14,'Ascension IsI','Ascension IsI',1);
        INSERT INTO country(id, name,code, status) VALUES(15,'Australia','Australia',1);
        INSERT INTO country(id, name,code, status) VALUES(16,'Austria','Austria',1);
        INSERT INTO country(id, name,code, status) VALUES(17,'Azerbaijan','Azerbaijan',1);
        INSERT INTO country(id, name,code, status) VALUES(18,'Azores IsI','Azores IsI',1);
        INSERT INTO country(id, name,code, status) VALUES(19,'Bahamas','Bahamas',1);
        INSERT INTO country(id, name,code, status) VALUES(20,'Bahrain','Bahrain',1);
        INSERT INTO country(id, name,code, status) VALUES(21,'Bangladesh','Bangladesh',1);
        INSERT INTO country(id, name,code, status) VALUES(22,'Barbados','Barbados',1);
        INSERT INTO country(id, name,code, status) VALUES(23,'Baleric IsI','Baleric IsI',1);
        INSERT INTO country(id, name,code, status) VALUES(24,'Belarus','Belarus',1);
        INSERT INTO country(id, name,code, status) VALUES(25,'Belgium','Belgium',1);
        INSERT INTO country(id, name,code, status) VALUES(26,'Belize','Belize',1);
        INSERT INTO country(id, name,code, status) VALUES(27,'Benin','Benin',1);
        INSERT INTO country(id, name,code, status) VALUES(28,'Bermuda','Bermuda',1);
        INSERT INTO country(id, name,code, status) VALUES(29,'Bhutan','Bhutan',1);
        INSERT INTO country(id, name,code, status) VALUES(30,'Bolivia','Bolivia',1);
        INSERT INTO country(id, name,code, status) VALUES(31,'Bosnia - Hecegovina','Bosnia - Hecegovina',1);
        INSERT INTO country(id, name,code, status) VALUES(32,'Bostwana','Bostwana',1);
        INSERT INTO country(id, name,code, status) VALUES(33,'Brazil','Brazil',1);
        INSERT INTO country(id, name,code, status) VALUES(34,'Bristish Virgin IsI','Bristish Virgin IsI',1);
        INSERT INTO country(id, name,code, status) VALUES(35,'Brunei','Brunei',1);
        INSERT INTO country(id, name,code, status) VALUES(36,'Bulgaria','Bulgaria',1);
        INSERT INTO country(id, name,code, status) VALUES(37,'Burkinafaso','Burkinafaso',1);
        INSERT INTO country(id, name,code, status) VALUES(38,'Burundi','Burundi',1);
        INSERT INTO country(id, name,code, status) VALUES(39,'Cambodia','Cambodia',1);
        INSERT INTO country(id, name,code, status) VALUES(40,'Cameroon','Cameroon',1);
        INSERT INTO country(id, name,code, status) VALUES(41,'Canada','Canada',1);
        INSERT INTO country(id, name,code, status) VALUES(42,'Canary IsI','Canary IsI',1);
        INSERT INTO country(id, name,code, status) VALUES(43,'Cape Verde','Cape Verde',1);
        INSERT INTO country(id, name,code, status) VALUES(44,'Cayman IsI','Cayman IsI',1);
        INSERT INTO country(id, name,code, status) VALUES(45,'Caribbean IsI','Caribbean IsI',1);
        INSERT INTO country(id, name,code, status) VALUES(46,'Central African Rep','Central African Rep',1);
        INSERT INTO country(id, name,code, status) VALUES(47,'Chad','Chad',1);
        INSERT INTO country(id, name,code, status) VALUES(48,'Chile','Chile',1);
        INSERT INTO country(id, name,code, status) VALUES(49,'China','China',1);
        INSERT INTO country(id, name,code, status) VALUES(50,'Christmas IsI','Christmas IsI',1);
        INSERT INTO country(id, name,code, status) VALUES(51,'Cocos IsI','Cocos IsI',1);
        INSERT INTO country(id, name,code, status) VALUES(52,'Colombia','Colombia',1);
        INSERT INTO country(id, name,code, status) VALUES(53,'Comoros','Comoros',1);
        INSERT INTO country(id, name,code, status) VALUES(54,'Congo, Rep.of the','Congo, Rep.of the',1);
        INSERT INTO country(id, name,code, status) VALUES(55,'Congo, DPR of the','Congo, DPR of the',1);
        INSERT INTO country(id, name,code, status) VALUES(56,'Cook IsI','Cook IsI',1);
        INSERT INTO country(id, name,code, status) VALUES(57,'Costa Rica','Costa Rica',1);
        INSERT INTO country(id, name,code, status) VALUES(58,'Croatia','Croatia',1);
        INSERT INTO country(id, name,code, status) VALUES(59,'Cuba','Cuba',1);
        INSERT INTO country(id, name,code, status) VALUES(60,'Cyprus','Cyprus',1);
        INSERT INTO country(id, name,code, status) VALUES(61,'Czech','Czech',1);
        INSERT INTO country(id, name,code, status) VALUES(62,'Denmark','Denmark',1);
        INSERT INTO country(id, name,code, status) VALUES(63,'Diego Garcia','Diego Garcia',1);
        INSERT INTO country(id, name,code, status) VALUES(64,'Djibouti','Djibouti',1);
        INSERT INTO country(id, name,code, status) VALUES(65,'Dominica IsI','Dominica IsI',1);
        INSERT INTO country(id, name,code, status) VALUES(66,'Dominican Rep','Dominican Rep',1);
        INSERT INTO country(id, name,code, status) VALUES(67,'East Timor','East Timor',1);
        INSERT INTO country(id, name,code, status) VALUES(68,'Ecuador','Ecuador',1);
        INSERT INTO country(id, name,code, status) VALUES(69,'Egypt','Egypt',1);
        INSERT INTO country(id, name,code, status) VALUES(70,'El Salvador','El Salvador',1);
        INSERT INTO country(id, name,code, status) VALUES(71,'Equatorial Guinea','Equatorial Guinea',1);
        INSERT INTO country(id, name,code, status) VALUES(72,'Estonia','Estonia',1);
        INSERT INTO country(id, name,code, status) VALUES(73,'Eritrea','Eritrea',1);
        INSERT INTO country(id, name,code, status) VALUES(74,'Ethiopia','Ethiopia',1);
        INSERT INTO country(id, name,code, status) VALUES(75,'Falkland IsI','Falkland IsI',1);
        INSERT INTO country(id, name,code, status) VALUES(76,'Faroe IsI','Faroe IsI',1);
        INSERT INTO country(id, name,code, status) VALUES(77,'Fiji','Fiji',1);
        INSERT INTO country(id, name,code, status) VALUES(78,'Finland','Finland',1);
        INSERT INTO country(id, name,code, status) VALUES(79,'France','France',1);
        INSERT INTO country(id, name,code, status) VALUES(80,'French Guiana','French Guiana',1);
        INSERT INTO country(id, name,code, status) VALUES(81,'French Polynesia','French Polynesia',1);
        INSERT INTO country(id, name,code, status) VALUES(82,'Gabon','Gabon',1);
        INSERT INTO country(id, name,code, status) VALUES(83,'Gambia','Gambia',1);
        INSERT INTO country(id, name,code, status) VALUES(84,'Georgia','Georgia',1);
        INSERT INTO country(id, name,code, status) VALUES(85,'Germany','Germany',1);
        INSERT INTO country(id, name,code, status) VALUES(86,'Ghana','Ghana',1);
        INSERT INTO country(id, name,code, status) VALUES(87,'Gibratar','Gibratar',1);
        INSERT INTO country(id, name,code, status) VALUES(88,'Greece','Greece',1);
        INSERT INTO country(id, name,code, status) VALUES(89,'Greenland','Greenland',1);
        INSERT INTO country(id, name,code, status) VALUES(90,'Grenada','Grenada',1);
        INSERT INTO country(id, name,code, status) VALUES(91,'Guadeloupe','Guadeloupe',1);
        INSERT INTO country(id, name,code, status) VALUES(92,'Guam','Guam',1);
        INSERT INTO country(id, name,code, status) VALUES(93,'Guatemala','Guatemala',1);
        INSERT INTO country(id, name,code, status) VALUES(94,'Guinea','Guinea',1);
        INSERT INTO country(id, name,code, status) VALUES(95,'Guinea Bissau','Guinea Bissau',1);
        INSERT INTO country(id, name,code, status) VALUES(96,'Guyana','Guyana',1);
        INSERT INTO country(id, name,code, status) VALUES(97,'Haiti','Haiti',1);
        INSERT INTO country(id, name,code, status) VALUES(98,'Hawaii','Hawaii',1);
        INSERT INTO country(id, name,code, status) VALUES(99,'Honduras','Honduras',1);
        INSERT INTO country(id, name,code, status) VALUES(100,'Hong Kong','Hong Kong',1);
        INSERT INTO country(id, name,code, status) VALUES(101,'Hungary','Hungary',1);
        INSERT INTO country(id, name,code, status) VALUES(102,'Iceland','Iceland',1);
        INSERT INTO country(id, name,code, status) VALUES(103,'India','India',1);
        INSERT INTO country(id, name,code, status) VALUES(104,'Indonesia','Indonesia',1);
        INSERT INTO country(id, name,code, status) VALUES(105,'Iran','Iran',1);
        INSERT INTO country(id, name,code, status) VALUES(106,'Iraq','Iraq',1);        
        INSERT INTO country(id, name,code, status) VALUES(108,'Israel','Israel',1);
        INSERT INTO country(id, name,code, status) VALUES(109,'Italy','Italy',1);
        INSERT INTO country(id, name,code, status) VALUES(110,'Ivory Coast','Ivory Coast',1);
        INSERT INTO country(id, name,code, status) VALUES(111,'Jamaica','Jamaica',1);
        INSERT INTO country(id, name,code, status) VALUES(112,'Japan','Japan',1);
        INSERT INTO country(id, name,code, status) VALUES(113,'Jordan','Jordan',1);
        INSERT INTO country(id, name,code, status) VALUES(114,'Kazakhstan','Kazakhstan',1);
        INSERT INTO country(id, name,code, status) VALUES(115,'Kenya','Kenya',1);
        INSERT INTO country(id, name,code, status) VALUES(116,'Kiribati','Kiribati',1);
        INSERT INTO country(id, name,code, status) VALUES(117,'Korea, DPR of','Korea, DPR of',1);
        INSERT INTO country(id, name,code, status) VALUES(118,'Korea, Rep of','Korea, Rep of',1);
        INSERT INTO country(id, name,code, status) VALUES(119,'Kuwait','Kuwait',1);
        INSERT INTO country(id, name,code, status) VALUES(120,'Kyrgyzstan','Kyrgyzstan',1);
        INSERT INTO country(id, name,code, status) VALUES(121,'Laos','Laos',1);
        INSERT INTO country(id, name,code, status) VALUES(122,'Latvia','Latvia',1);
        INSERT INTO country(id, name,code, status) VALUES(123,'Lebanon','Lebanon',1);
        INSERT INTO country(id, name,code, status) VALUES(124,'Lesotho','Lesotho',1);
        INSERT INTO country(id, name,code, status) VALUES(125,'Liberia','Liberia',1);
        INSERT INTO country(id, name,code, status) VALUES(126,'Libya','Libya',1);
        INSERT INTO country(id, name,code, status) VALUES(127,'Liechtenstein','Liechtenstein',1);
        INSERT INTO country(id, name,code, status) VALUES(128,'Lithuania','Lithuania',1);
        INSERT INTO country(id, name,code, status) VALUES(129,'Luxembourg','Luxembourg',1);
        INSERT INTO country(id, name,code, status) VALUES(130,'Macao','Macao',1);
        INSERT INTO country(id, name,code, status) VALUES(131,'Macedonia','Macedonia',1);
        INSERT INTO country(id, name,code, status) VALUES(132,'Madagasca','Madagasca',1);
        INSERT INTO country(id, name,code, status) VALUES(133,'Madeira','Madeira',1);
        INSERT INTO country(id, name,code, status) VALUES(134,'Malawi','Malawi',1);
        INSERT INTO country(id, name,code, status) VALUES(135,'Malaysia','Malaysia',1);
        INSERT INTO country(id, name,code, status) VALUES(136,'Maldives','Maldives',1);
        INSERT INTO country(id, name,code, status) VALUES(137,'Mali','Mali',1);
        INSERT INTO country(id, name,code, status) VALUES(138,'Malta','Malta',1);
        INSERT INTO country(id, name,code, status) VALUES(139,'Marshall IsI','Marshall IsI',1);
        INSERT INTO country(id, name,code, status) VALUES(140,'Martinique','Martinique',1);
        INSERT INTO country(id, name,code, status) VALUES(141,'Mauritania','Mauritania',1);
        INSERT INTO country(id, name,code, status) VALUES(142,'Mauritius','Mauritius',1);
        INSERT INTO country(id, name,code, status) VALUES(143,'Mayotte IsI','Mayotte IsI',1);
        INSERT INTO country(id, name,code, status) VALUES(144,'Mexico','Mexico',1);
        INSERT INTO country(id, name,code, status) VALUES(145,'Micronesia','Micronesia',1);
        INSERT INTO country(id, name,code, status) VALUES(146,'Midway Islands','Midway Islands',1);
        INSERT INTO country(id, name,code, status) VALUES(147,'Moldova,','Moldova,',1);
        INSERT INTO country(id, name,code, status) VALUES(148,'Monaco','Monaco',1);
        INSERT INTO country(id, name,code, status) VALUES(149,'Mongolia,','Mongolia,',1);
        INSERT INTO country(id, name,code, status) VALUES(150,'Montserrat','Montserrat',1);
        INSERT INTO country(id, name,code, status) VALUES(151,'Morocco','Morocco',1);
        INSERT INTO country(id, name,code, status) VALUES(152,'Mozambique','Mozambique',1);
        INSERT INTO country(id, name,code, status) VALUES(153,'Myanmar ','Myanmar ',1);
        INSERT INTO country(id, name,code, status) VALUES(154,'Namibia','Namibia',1);
        INSERT INTO country(id, name,code, status) VALUES(155,'Nauru,','Nauru,',1);
        INSERT INTO country(id, name,code, status) VALUES(156,'Nepal','Nepal',1);
        INSERT INTO country(id, name,code, status) VALUES(157,'Netherlands','Netherlands',1);
        INSERT INTO country(id, name,code, status) VALUES(158,'New Caledonia,','New Caledonia,',1);
        INSERT INTO country(id, name,code, status) VALUES(159,'New Zealand','New Zealand',1);
        INSERT INTO country(id, name,code, status) VALUES(160,'Nicaragua','Nicaragua',1);
        INSERT INTO country(id, name,code, status) VALUES(161,'Niger','Niger',1);
        INSERT INTO country(id, name,code, status) VALUES(162,'Nigeria ','Nigeria ',1);
        INSERT INTO country(id, name,code, status) VALUES(163,'Niue IsI','Niue IsI',1);
        INSERT INTO country(id, name,code, status) VALUES(164,'Norfolk IsI','Norfolk IsI',1);
        INSERT INTO country(id, name,code, status) VALUES(165,'Norway','Norway',1);
        INSERT INTO country(id, name,code, status) VALUES(166,'Oman','Oman',1);
        INSERT INTO country(id, name,code, status) VALUES(167,'Pakistan','Pakistan',1);
        INSERT INTO country(id, name,code, status) VALUES(168,'Palau','Palau',1);
        INSERT INTO country(id, name,code, status) VALUES(169,'Palestine','Palestine',1);
        INSERT INTO country(id, name,code, status) VALUES(170,'Panama','Panama',1);
        INSERT INTO country(id, name,code, status) VALUES(172,'Papua New Guinea','Papua New Guinea',1);
        INSERT INTO country(id, name,code, status) VALUES(173,'Paraguay','Paraguay',1);
        INSERT INTO country(id, name,code, status) VALUES(174,'Peru','Peru',1);
        INSERT INTO country(id, name,code, status) VALUES(175,'Philippines','Philippines',1);
        INSERT INTO country(id, name,code, status) VALUES(176,'Poland','Poland',1);
        INSERT INTO country(id, name,code, status) VALUES(177,'Portugal','Portugal',1);
        INSERT INTO country(id, name,code, status) VALUES(178,'Puerto Rico','Puerto Rico',1);
        INSERT INTO country(id, name,code, status) VALUES(179,'Quatar','Quatar',1);
        INSERT INTO country(id, name,code, status) VALUES(180,'Reunion','Reunion',1);
        INSERT INTO country(id, name,code, status) VALUES(181,'Romania','Romania',1);
        INSERT INTO country(id, name,code, status) VALUES(182,'Russia','Russia',1);
        INSERT INTO country(id, name,code, status) VALUES(183,'Ruwanda','Ruwanda',1);
        INSERT INTO country(id, name,code, status) VALUES(184,'Saipan ( Mariana )','Saipan ( Mariana )',1);
        INSERT INTO country(id, name,code, status) VALUES(185,'San Marino','San Marino',1);
        INSERT INTO country(id, name,code, status) VALUES(186,'Sao Tome and Principe','Sao Tome and Principe',1);
        INSERT INTO country(id, name,code, status) VALUES(187,'Saudi Arabia','Saudi Arabia',1);
        INSERT INTO country(id, name,code, status) VALUES(188,'Senegal','Senegal',1);
        INSERT INTO country(id, name,code, status) VALUES(189,'Seychelles','Seychelles',1);
        INSERT INTO country(id, name,code, status) VALUES(190,'Sierra Leone','Sierra Leone',1);
        INSERT INTO country(id, name,code, status) VALUES(191,'Singapore','Singapore',1);
        INSERT INTO country(id, name,code, status) VALUES(192,'Slovakia','Slovakia',1);
        INSERT INTO country(id, name,code, status) VALUES(193,'Slovenia','Slovenia',1);
        INSERT INTO country(id, name,code, status) VALUES(194,'Solomon IsI','Solomon IsI',1);
        INSERT INTO country(id, name,code, status) VALUES(195,'Somalia','Somalia',1);
        INSERT INTO country(id, name,code, status) VALUES(196,'South Africa','South Africa',1);
        INSERT INTO country(id, name,code, status) VALUES(197,'Spain','Spain',1);
        INSERT INTO country(id, name,code, status) VALUES(198,'Spanish North Africa','Spanish North Africa',1);
        INSERT INTO country(id, name,code, status) VALUES(199,'Sri Lanka','Sri Lanka',1);
        INSERT INTO country(id, name,code, status) VALUES(200,'St Helena','St Helena',1);
        INSERT INTO country(id, name,code, status) VALUES(201,'St Kitts and Nevis','St Kitts and Nevis',1);
        INSERT INTO country(id, name,code, status) VALUES(202,'St Lucia','St Lucia',1);
        INSERT INTO country(id, name,code, status) VALUES(203,'St Pierre and Miquelon','St Pierre and Miquelon',1);
        INSERT INTO country(id, name,code, status) VALUES(204,'St Vicent & Grenadines','St Vicent & Grenadines',1);
        INSERT INTO country(id, name,code, status) VALUES(205,'Sudan','Sudan',1);
        INSERT INTO country(id, name,code, status) VALUES(206,'Surinam','Surinam',1);
        INSERT INTO country(id, name,code, status) VALUES(207,'Swaziland','Swaziland',1);
        INSERT INTO country(id, name,code, status) VALUES(208,'Sweeden','Sweeden',1);
        INSERT INTO country(id, name,code, status) VALUES(209,'Switzerland','Switzerland',1);
        INSERT INTO country(id, name,code, status) VALUES(210,'Syria','Syria',1);
        INSERT INTO country(id, name,code, status) VALUES(211,'Taiwan','Taiwan',1);
        INSERT INTO country(id, name,code, status) VALUES(212,'Tajikistan','Tajikistan',1);
        INSERT INTO country(id, name,code, status) VALUES(213,'Tanzania','Tanzania',1);
        INSERT INTO country(id, name,code, status) VALUES(214,'Thailand','Thailand',1);
        INSERT INTO country(id, name,code, status) VALUES(215,'Togo','Togo',1);
        INSERT INTO country(id, name,code, status) VALUES(216,'Tonga','Tonga',1);
        INSERT INTO country(id, name,code, status) VALUES(217,'Tokelau','Tokelau',1);
        INSERT INTO country(id, name,code, status) VALUES(218,'Trinidad & Tobaco','Trinidad & Tobaco',1);
        INSERT INTO country(id, name,code, status) VALUES(219,'Tunisia','Tunisia',1);
        INSERT INTO country(id, name,code, status) VALUES(220,'Turkey','Turkey',1);
        INSERT INTO country(id, name,code, status) VALUES(221,'Turkmenistan','Turkmenistan',1);
        INSERT INTO country(id, name,code, status) VALUES(222,'Turks and Caicos IsI','Turks and Caicos IsI',1);
        INSERT INTO country(id, name,code, status) VALUES(223,'Tuvalu','Tuvalu',1);
        INSERT INTO country(id, name,code, status) VALUES(224,'Uganda','Uganda',1);
        INSERT INTO country(id, name,code, status) VALUES(225,'Ukraine','Ukraine',1);
        INSERT INTO country(id, name,code, status) VALUES(226,'United Arab Emirates','United Arab Emirates',1);
        INSERT INTO country(id, name,code, status) VALUES(227,'United Kingdom','United Kingdom',1);
        INSERT INTO country(id, name,code, status) VALUES(228,'Uruguay','Uruguay',1);
        INSERT INTO country(id, name,code, status) VALUES(229,'USA','USA',1);
        INSERT INTO country(id, name,code, status) VALUES(230,'Uzbekistan','Uzbekistan',1);
        INSERT INTO country(id, name,code, status) VALUES(231,'Vanuatu','Vanuatu',1);
        INSERT INTO country(id, name,code, status) VALUES(232,'Vatican City','Vatican City',1);
        INSERT INTO country(id, name,code, status) VALUES(233,'Venezuela','Venezuela',1);
        INSERT INTO country(id, name,code, status) VALUES(234,'Viet Nam','Viet Nam',1);
        INSERT INTO country(id, name,code, status) VALUES(235,'Wake IsI','Wake IsI',1);
        INSERT INTO country(id, name,code, status) VALUES(236,'Wallis & Futuna IsI','Wallis & Futuna IsI',1);
        INSERT INTO country(id, name,code, status) VALUES(237,'Western Sahara','Western Sahara',1);
        INSERT INTO country(id, name,code, status) VALUES(238,'Western Samoa','Western Samoa',1);
        INSERT INTO country(id, name,code, status) VALUES(239,'Yemen Republic','Yemen Republic',1);
        INSERT INTO country(id, name,code, status) VALUES(240,'Yugoslavia','Yugoslavia',1);
        INSERT INTO country(id, name,code, status) VALUES(241,'Zambia','Zambia',1);
        INSERT INTO country(id, name,code, status) VALUES(242,'Zimbabue','Zimbabue',1);
        INSERT INTO country(id, name,code, status) VALUES(245,'Vietnam','Vietnam',1);
        ";
        $this->_executeMultiRaw($query);
        // update position 234: vietnam, 118: Hàn Quốc
        $query = "UPDATE country SET position = 1 WHERE id IN (234, 118);";
        $this->_executeMultiRaw($query);
    }
}
